### ISSUE TITLE
Replace 3D model?

### ISSUE THREAD

**Issue by violetforest** [keijiro/Mirage#2]
Hey, thanks for uploading this project. Could you please help me figure out how to replace the 3D model (winged victory lucy left/right) ? I see the LucyRenderer and LucyMeshEditor scripts and that they are looking in the assets folder but if you could help me figure out exacty how they are getting that specific model that would be great. Thanks!

**Comment by keijiro** [comment]
- Import a model to be replaced with Lucy.
- Select a mesh from the imported model asset.
- Right click menu -> Mirage -> Lucy -> Convert Mesh
- Set the converted mesh to LucyRenderer in the scene.

The mesh properties of LucyRenderer are hidden in the inspector, so that you have to modify the script to expose these properties.

https://github.com/keijiro/Mirage/blob/master/Assets/Mirage/Lucy/LucyRenderer.cs#L56
